### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by SzotsGabor** [fabianvdW/Scam#40]
Hi guys,

Last commit is almost one year old. Are you still working on this?

**Comment by fabianvdW** [comment]
No, no one is currently working on this Gabor. But perhaps I will find some time and motivation in the future again.

**Comment by SzotsGabor** [comment]
> No, no one is currently working on this Gabor. But perhaps I will find some time and motivation in the future again.

I will follow you in the hope there will be news sooner or later. Until then I'm going to include the current version in some of my tournaments.

**Comment by fabianvdW** [comment]
Thank you Gabor. I forgot the strength of Scam, but I think it should be around ~2000? Not sure.

**Comment by SzotsGabor** [comment]
> Thank you Gabor. I forgot the strength of Scam, but I think it should be around ~2000? Not sure.

Uh, then we may have made a mistake when compiling. My quick test showed ~1300, while Ray said he thought it was closer to 1000.

**Comment by fabianvdW** [comment]
This might also totally possible, I thought I remembered that it was a bit stronger, but perhaps it was not. The evaluation is really bad compared to the search, it only contains a PSQT.
